# Generated by Django 2.1.7 on 2019-05-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20190518_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='description_html',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='slug',
        ),
    ]
